# Generated by Django 4.2.5 on 2023-09-14 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 20, 57, 5, 168150, tzinfo=datetime.timezone.utc)),
        ),
    ]
