# Generated by Django 4.2.5 on 2023-09-14 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0006_alter_gif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
