# Generated by Django 4.2.5 on 2023-09-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0007_alter_gif_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='categories',
            field=models.ManyToManyField(related_name='gifs', to='gifs.category'),
        ),
    ]
