# Generated by Django 4.2.5 on 2023-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0008_alter_gif_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
