# Generated by Django 4.2.6 on 2023-10-27 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_alter_department_department_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_admin',
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ManyToManyField(related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
