# Generated by Django 4.2.5 on 2023-09-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
