# Generated by Django 4.2.5 on 2023-11-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0003_remove_figure_image_url_figure_notoriety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figureimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='figureimage',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
