# Generated by Django 4.2.5 on 2023-11-08 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0004_figureimage_name_alter_figureimage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figure', to='fight.figure'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
    ]
