# Generated by Django 4.2.5 on 2023-11-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0005_battle_figure_alter_battle_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='fight.figureimage'),
        ),
    ]
