# Generated by Django 4.2.5 on 2023-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0006_battle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='luck',
            field=models.IntegerField(default=0),
        ),
    ]
