# Generated by Django 4.2.5 on 2023-11-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0007_figure_luck'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
