# Generated by Django 4.2.5 on 2023-11-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0008_battle_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figureimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
