# Generated by Django 4.2.5 on 2023-09-24 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_created_in_country_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='films.film')),
                ('image', models.ImageField(upload_to='posters/')),
                ('explanation_img', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
