# Generated by Django 4.2.5 on 2023-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='explanation_img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
