# Generated by Django 4.2.5 on 2023-09-24 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_poster_explanation_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='poster', serialize=False, to='films.film'),
        ),
    ]
