# Generated by Django 4.2.5 on 2023-09-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_poster_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films/posters/'),
        ),
    ]
