# Generated by Django 4.2.5 on 2023-09-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_guesses',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
    ]
