# Generated by Django 4.2.5 on 2023-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0003_game_num_guesses_alter_game_current_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_word',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='shuffled_word',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
