# Generated by Django 4.2.5 on 2023-09-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0004_alter_game_current_word_alter_game_shuffled_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_message',
            field=models.CharField(default='', max_length=50),
        ),
    ]
