# Generated by Django 4.2.4 on 2023-08-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount_of_money', models.IntegerField(default=1000)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name_character', models.CharField()),
                ('species', models.CharField()),
                ('house', models.CharField()),
                ('image_url', models.CharField()),
                ('date_of_birth', models.CharField()),
                ('patronus', models.CharField()),
                ('price', models.IntegerField(default=258)),
                ('xp_points', models.IntegerField(default=1)),
                ('current_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='cards.user')),
                ('previous_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='cards.user')),
            ],
        ),
    ]
